[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
extend-select = ["I"]        # isort‑compatible import ordering

[tool.mypy]
strict = true
no_implicit_optional = true
warn_unused_ignores = true

[tool.flake8]
max-line-length = 100